// One-time, asserted integration of the new local adapter into the existing UI.
// CI verifies the resulting files before committing them to the feature branch.
const fs=require('fs')
function patch(path,before,after) {
  const source=fs.readFileSync(path,'utf8')
  if (!source.includes(before)) throw new Error('Integration anchor changed: '+path+' / '+before.slice(0,80))
  fs.writeFileSync(path,source.replace(before,after))
}
function append(path,content) {fs.appendFileSync(path,content)}
const pkg=JSON.parse(fs.readFileSync('package.json','utf8'))
pkg.dependencies['@sqlite.org/sqlite-wasm']='3.53.0-build1'
pkg.dependencies.fzstd='0.1.1'
pkg.scripts['test:wcdb']='node --test tests/wcdb.test.mjs'
fs.writeFileSync('package.json',JSON.stringify(pkg,null,2)+'\n')
patch('src/lib/wcdb/input.mjs','for (const file of Array.from(files || [])) {','for (const entry of Array.from(files || [])) {\n    const file=entry.file || entry')
patch('src/lib/wcdb/input.mjs','string(file.webkitRelativePath || file.name)','string(entry.path || file.webkitRelativePath || file.name)')
patch('src/lib/wcdb/import.mjs',"report.contacts=rows(index,", "const extent=rows(index,'SELECT MIN(timeMs) first,MAX(timeMs) last FROM messages')[0]\n    report.firstMessageAt=extent.first?new Date(extent.first).toISOString():null\n    report.lastMessageAt=extent.last?new Date(extent.last).toISOString():null\n    report.contacts=rows(index,")
patch('src/lib/wcdb/storage.mjs',"if (previous && previous!==path) pool.unlink(previous)","if (previous && previous!==path) {try {pool.unlink(previous)} catch (_) { /* Published archive is valid; old orphan is cleaned on next open. */ }}")
patch('src/lib/wcdb/sql.mjs',"db.queryDeadline=Infinity", "if (sqlite.capi.sqlite3_limit) {\n    sqlite.capi.sqlite3_limit(db.pointer,sqlite.capi.SQLITE_LIMIT_LENGTH,4*1024*1024)\n    sqlite.capi.sqlite3_limit(db.pointer,sqlite.capi.SQLITE_LIMIT_SQL_LENGTH,128*1024)\n    sqlite.capi.sqlite3_limit(db.pointer,sqlite.capi.SQLITE_LIMIT_COLUMN,512)\n    sqlite.capi.sqlite3_limit(db.pointer,sqlite.capi.SQLITE_LIMIT_ATTACHED,0)\n  }\n  db.queryDeadline=Infinity")
patch('src/lib/workspace.js',"import api from '@/api'","import api from '@/api'\nimport { isLocal } from '@/data-sources/source'")
patch('src/lib/workspace.js','const sessions=state.sessions.slice(0,10),',"if(isLocal.value){const result=await api.getLocalAnalysis({days});if(epoch!==generation)throw new Error('数据来源已变更。');sampleCache.set(days,result);return result}\n  const sessions=state.sessions.slice(0,10),")
patch('src/lib/useSample.js','computed(()=>analyze(sample.value?.logs||[],days.value,clock()))','computed(()=>sample.value?.stats || analyze(sample.value?.logs||[],days.value,clock()))')
append('src/styles/main.css',"\n@import './local-archive.css';\n")
patch('src/router/index.js',"children: [","children: [\n  { path: '/sources', name: 'Sources', component: () => import('@/views/Sources.vue'), meta: { title: '数据来源' } },")
patch('src/layout/index.vue',"import { getApiBase, setApiBase } from '@/api'","import { getApiBase, setApiBase } from '@/api'\nimport { isLocal,selectSource } from '@/data-sources/source'")
patch('src/layout/index.vue',"{label:'工作空间',items:[","{label:'工作空间',items:[{path:'/sources',label:'数据来源',icon:'folder'},")
patch('src/layout/index.vue',"computed(()=>demoEnabled?'演示数据':workspace.loading?","computed(()=>demoEnabled?'演示数据':isLocal.value?'本地档案':workspace.loading?")
patch('src/layout/index.vue','setApiBase(endpoint.value);resetWorkspace();','setApiBase(endpoint.value);await selectSource(\'http\');resetWorkspace();')
patch('src/layout/index.vue','只连接你配置的数据服务','本地读取或连接你的服务')
patch('src/layout/index.vue','使用后端关键词查询','搜索当前数据来源中的聊天内容')
patch('src/layout/index.vue','仅在浏览器中保存服务地址和外观设置，不保存聊天正文。','HTTP 模式只保存服务地址和外观设置，不缓存聊天正文。本地数据库模式由你确认后单独保存档案。')
patch('src/layout/index.vue','<form id="connection-form"','<p class="scope-note">已有明文数据库？<router-link to="/sources" @click="settingsOpen=false">前往数据来源导入</router-link></p><form id="connection-form"')
patch('src/views/ChatLog.vue',"import api from '@/api'","import api from '@/api'\nimport { isLocal } from '@/data-sources/source'")
patch('src/views/ChatLog.vue','const matchLocal=logs=>logs.filter','const matchLocal=logs=>isLocal.value?logs:logs.filter')
patch('src/views/ChatLog.vue','const params=()=>({talker:','const params=()=>({...(isLocal.value?{keywords:extraKeywords.value,match:matchMode.value}:{}),talker:')
patch('src/views/ChatLog.vue','<MessageContent :content="message.content"','<MessageContent :message="message" :content="message.content"')
patch('src/views/ChatLog.vue','alive&&demoEnabled&&!searched.value','alive&&(demoEnabled||isLocal.value)&&!searched.value')
patch('src/views/ChatLog.vue','return {workspace,sessionQuery,','return {isLocal,workspace,sessionQuery,')
patch('src/views/ChatLog.vue','· 本页{{ matchMode','· {{ isLocal?\'本地索引\':\'本页\' }}{{ matchMode')
patch('src/views/ChatLog.vue','<div v-if="extraKeywords.length" class="result-note">多关键词','<div v-if="isLocal && extraKeywords.length" class="result-note">追加关键词筛选覆盖整个已导入索引，支持中文短词与 AND / OR。</div><div v-if="!isLocal && extraKeywords.length" class="result-note">多关键词')
patch('src/views/ChatLog.vue','<span>本页追加关键词筛选</span>','<span>{{ isLocal?\'本地索引追加关键词\':\'本页追加关键词筛选\' }}</span>')
patch('src/views/ChatLog.vue','<p>仅对当前加载页执行匹配。全量关键词查询请使用主搜索框。</p>','<p>{{ isLocal?\'对整个已导入索引执行匹配。未解码正文不会被当作有效搜索内容。\':\'仅对当前加载页执行匹配。全量关键词查询请使用主搜索框。\' }}</p>')
patch('src/views/ChatLog.vue','<span>本页匹配规则</span>','<span>{{ isLocal?\'索引匹配规则\':\'本页匹配规则\' }}</span>')
patch('src/views/ChatLog.vue','追加关键词只对本次读取结果过滤，不保证穷尽所有匹配。','{{ isLocal?\'本地模式先在整个索引中筛选，再读取最多 5,000 条匹配记录。\':\'追加关键词只对本次读取结果过滤，不保证穷尽所有匹配。\' }}')
patch('src/views/Analytics.vue',"import { number,csvString,download,dateKey }", "import api from '@/api'\nimport { isLocal } from '@/data-sources/source'\nimport { number,csvString,download,dateKey,rangeDays }")
patch('src/views/Analytics.vue','const exportData=()=>{download(',"const exportData=async()=>{if(isLocal.value){try{const result=await api.getChatLogs({time:rangeDays(sample.days.value,new Date(sample.sample.value.end)),limit:5000});download(csvString(result.data,[{key:'senderName',label:'发送者'},{key:'time',label:'时间'},{key:'content',label:'内容'}]),'chatlog-local-analysis.csv','text/csv;charset=utf-8');notify('已导出 '+result.data.length+' 条；当前范围共 '+result.total+' 条，单次上限 5,000 条。')}catch(e){notify(e.message)}return}download(")
patch('src/views/Analytics.vue','所有统计均基于已读取样本。','统计范围与数据覆盖情况见下方说明。')
patch('src/components/charts/TypeDonut.vue',"'var(--subtle)']","'var(--subtle)','var(--red)','var(--accent-strong)','var(--ink)','var(--muted)']")
for(const file of ['src/views/Sources.vue','src/views/LocalMedia.vue'])patch(file,' subtitle=',' description=')
patch('src/views/LocalMedia.vue','class="segmented"','class="segment-control segmented"')
console.log('Local archive integration prepared. Verify tests before publishing.')
fs.unlinkSync(__filename)
