// One-time review fixes. CI tests the resulting source before publishing it.
const fs=require('fs')
function patch(path,before,after){const source=fs.readFileSync(path,'utf8');if(!source.includes(before))throw new Error('Review anchor changed: '+path+' / '+before.slice(0,60));fs.writeFileSync(path,source.replace(before,after))}
function replaceAll(path,before,after){const source=fs.readFileSync(path,'utf8');if(!source.includes(before))throw new Error('Review anchor changed: '+path);fs.writeFileSync(path,source.split(before).join(after))}
patch('src/lib/wcdb/statistics.mjs','return {local:true,days,end:anchor.toISOString(),','return {local:true,days,end:anchor.toISOString(),endDate:dayKey(anchor),')
patch('src/components/ui/SampleNotice.vue',"sample.end?.slice(0,10)","sample.endDate || sample.end?.slice(0,10)")
patch('src/views/Dashboard.vue',"const metric=(key)=>", "const referenceDate=()=>sample.sample.value?.local?new Date(sample.sample.value.end):clock();const metric=(key)=>")
patch('src/views/Dashboard.vue',"{label:'近 7 天活跃会话'","{label:sample.sample.value?.local?'档案末 7 天活跃会话':'近 7 天活跃会话'")
patch('src/views/Dashboard.vue',"d&&d<=clock()&&d>=new Date(clock().getTime()-7*86400000)","d&&d<=referenceDate()&&d>=new Date(referenceDate().getTime()-7*86400000)")
patch('src/views/Dashboard.vue','条样本消息 · 近 {{ days }} 天','条已读取消息 · {{ days }} 天')
patch('src/views/Dashboard.vue','与左侧使用相同时间范围和样本','与左侧使用相同时间范围和数据来源')
patch('src/views/Dashboard.vue','接入 chatlog 服务后，对话会显示在这里。','连接服务或导入本地数据库后，对话会显示在这里。')
replaceAll('src/views/Analytics.vue','样本消息','已读取消息')
replaceAll('src/views/Analytics.vue','正在读取并分析样本','正在读取并分析记录')
replaceAll('src/views/Analytics.vue','按样本内发送者去重','按已识别的发送者去重')
replaceAll('src/views/Analytics.vue','仅反映当前样本','仅反映当前数据覆盖范围')
replaceAll('src/views/Analytics.vue','样本里没有群聊','当前范围没有群聊')
patch('src/views/Analytics.vue','/>导出样本</button>','/>导出当前范围</button>')
patch('src/views/Analytics.vue','仅对已采样的群聊排序，非全部群排行','对当前数据覆盖范围内的群聊排序')
patch('src/layout/index.vue',"connectionLabel!=='已连接' && !demoEnabled","connectionLabel!=='已连接' && connectionLabel!=='本地档案' && !demoEnabled")
patch('tests/make-local-fixtures.py',"'unparsed':8","'unparsed':4")
patch('tests/browser-local.py',"page.set_viewport_size({'width':390,'height':844})\n      page.screenshot", "page.set_viewport_size({'width':390,'height':844})\n      page.wait_for_function(\"document.querySelector('.sidebar').getBoundingClientRect().right<=1\")\n      page.screenshot")
patch('tests/browser-local.py',"      checked('390px mobile source manager has no horizontal overflow')\n      page.set_viewport_size", "      checked('390px mobile source manager has no horizontal overflow')\n      for route in ['dashboard','chatlog','analytics','contacts','chatrooms','sessions','media']:\n        page.goto('http://127.0.0.1:8780/'+route);page.wait_for_timeout(1000)\n        assert page.locator('body').evaluate('(el)=>el.scrollWidth<=window.innerWidth+1'),route\n        assert not page.locator('.state-panel.error').count(),page.locator('body').inner_text()\n        checked('local source mobile route: '+route)\n      page.goto('http://127.0.0.1:8780/sources')\n      expect(page.locator('.source-metrics strong').first).to_have_text('60')\n      page.set_viewport_size")
patch('tests/browser-local.py',"      page.locator('.source-danger input').check()", "      page.locator('.topbar').get_by_role('button',name='切换深色模式',exact=True).click()\n      expect(page.locator('html')).to_have_attribute('data-theme','dark')\n      page.screenshot(path=str(OUT/'sources-dark.png'),full_page=True)\n      checked('local source manager dark theme')\n      page.locator('.source-danger input').check()")
for(const path of ['README.md','README_EN.md','docs/LOCAL-ARCHIVE.md']) {
 const source=fs.readFileSync(path,'utf8')
 fs.writeFileSync(path,source.replace('node --test tests/core.test.mjs tests/wcdb.test.mjs','node --test tests/*.test.mjs'))
}
console.log('Reviewed archive scope labels, dates and mobile screenshot readiness.')
fs.unlinkSync(__filename)
